name: Deploy USA site (root)
on:
  push:
    branches: [usa]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Firebase gizlileri
      VITE_FB_APIKEY: ${{ secrets.VITE_FB_APIKEY }}
      VITE_FB_AUTHDOMAIN: ${{ secrets.VITE_FB_AUTHDOMAIN }}
      VITE_FB_PROJECTID: ${{ secrets.VITE_FB_PROJECTID }}
      VITE_FB_STORAGE: ${{ secrets.VITE_FB_STORAGE }}
      VITE_FB_SENDER: ${{ secrets.VITE_FB_SENDER }}
      VITE_FB_APPID: ${{ secrets.VITE_FB_APPID }}
      VITE_FB_MEAS: ${{ secrets.VITE_FB_MEAS }}
      VITE_FB_DBURL: ${{ secrets.VITE_FB_DBURL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build           # /city-invade-pixel-map/ tabanıyla USA derlenir
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with: { path: dist }         # dist'i doğrudan köke koy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages       # prod ortama dağıt
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4 